spring:
  datasource:
    url: jdbc:mysql://localhost:3306/church_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: church_user
    password: bhch8511
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

logging:
  level:
    com.banghwa: INFO
  file:
    name: /app/church/logs/church.log